name: Release CI
on:
  push:
    branches: [release, alpha, beta, rc]

jobs:
  release:
    if: github.ref == 'refs/heads/release'  # 仅 release 发布
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm build
      - run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}  # 设置 npm 发布 token
      - run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
