name: Release CI
on:
  push:
    branches: [main, alpha, beta, rc]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Verify NPM_TOKEN
        run: |
            npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
            npm whoami --registry=https://registry.npmjs.org
  release:
    needs: test
    if: github.ref == 'refs/heads/main'  # 仅 main 发布
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
